[[main]]
none = "none"

[[footer]]
none = "none"

[[footer]]
url = "https://instagram.com/bluevatech/"
identifier = "instagram"
pre = "instagram"
weight = 9_999

[[footer]]
url = "https://bsky.app/profile/bluevatech.bsky.social"
identifier = "bluesky"
pre = "bluesky"
weight = 9_999

[[footer]]
url = "https://x.com/BluevaTech"
identifier = "x-twitter"
pre = "x-twitter"
weight = 9_999

[[footer]]
url = "https://www.linkedin.com/company/blueva-technologies/"
identifier = "linkedin"
pre = "linkedin"
weight = 9_999

[[footer]]
url = "https://www.tiktok.com/@bluevatech"
identifier = "tiktok"
pre = "tiktok"
weight = 9_999
